kibana:
  image: kibana:4.3.0
  ports:
    - 5601:5601
  links:
    - elasticsearch
  environment:
    ELASTICSEARCH_URL: http://elasticsearch:9200 

elasticsearch:
  image: elasticsearch:2.1.0
  volumes:
   - "/esdata"
